blog_pageCategorie:
    resource: "@blogBundle/Resources/config/routing/categories.yml"
    prefix:   /admin/Categories

blog_pagePhoto:
    resource: "@blogBundle/Resources/config/routing/photos.yml"
    prefix:   /admin/Photos

blog_homepage:
    path:     /
    defaults: { _controller: blogBundle:Default:index }

blog_admin:
    path:     /admin
    defaults: { _controller: blogBundle:Admin:index }